### ISSUE TITLE
Error running bakthat on freebsd9.1

### ISSUE THREAD

**Issue by acardenes** [tsileo/bakthat#25]
Hi, first of all I wanted to thak you for your great job on bakthat. 
I think I found a bug on a default install on FreeBSD, after installing and testing that everything worked on a Fedora box, I installed on FreeBSD 9.1 using pip install bakthat and i get this error:

Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 8, in <module>
    load_entry_point('bakthat==0.4.5', 'console_scripts', 'bakthat')()
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 318, in load_entry_point
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2221, in load_entry_point
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1954, in load
  File "/usr/local/lib/python2.7/site-packages/bakthat/**init**.py", line 23, in <module>
    from bakthat.backends import GlacierBackend, S3Backend, RotationConfig
  File "/usr/local/lib/python2.7/site-packages/bakthat/backends.py", line 16, in <module>
    from bakthat.models import Inventory, Jobs
  File "/usr/local/lib/python2.7/site-packages/bakthat/models.py", line 1, in <module>
    import peewee
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 97, in <module>
    raise ImproperlyConfigured('Either sqlite3, psycopg2 or MySQLdb must be installed')
peewee.ImproperlyConfigured: Either sqlite3, psycopg2 or MySQLdb must be installed

Thanks

**Comment by tsileo** [comment]
Hi,

Thanks for your feedback, 

I think the issue comes from py-sqlite3 not being present, this is a FreeBSD related issue, I found this link: http://stackoverflow.com/a/7973852, can you try to install **py-sqlite3** and try to reinstall bakthat ?

Keep me updated, and show me how you installed py-sqlite3 so I can update the docs for future FreeBSD users.

Thanks!

**Comment by acardenes** [comment]
Hey, thanks a lot for the quick answer, I installed /usr/ports/databases/py-sqlite3 with the usual make install clean and after that also installed requests module usingpip install requests.

Everything seems to be working fine now.

Thanks!
