### ISSUE TITLE
ImportError: no module named glacier.exceptions

### ISSUE THREAD

**Issue by kgifford-jobsync** [tsileo/bakthat#35]
I'm trying to install and configure Bakthat and am receiving the following error:

```
ubuntu@ip-10-168-78-253:~$ bakthat configure
Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.6.0', 'console_scripts', 'bakthat')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 346, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2516, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2210, in load
    for ext in extras:
  File "/usr/local/lib/python2.7/dist-packages/bakthat-0.6.0-py2.7.egg/bakthat/__init__.py", line 25, in <module>
    from bakthat.backends import GlacierBackend, S3Backend, RotationConfig, SwiftBackend
  File "/usr/local/lib/python2.7/dist-packages/bakthat-0.6.0-py2.7.egg/bakthat/backends.py", line 13, in <module>
    from boto.glacier.exceptions import UnexpectedHTTPResponseError
ImportError: No module named glacier.exceptions
```

System is Ubuntu 12.04 (on EC2), running Python 2.7.3. I just did a fresh install of setuptools following these instructions (https://pypi.python.org/pypi/setuptools/0.7.2#unix-based-systems-including-mac-os-x), and pip following these instructions (http://www.pip-installer.org/en/latest/installing.html#using-get-pip).

Any ideas on what I can do to get this working?

**Comment by kgifford-jobsync** [comment]
My copy of boto was out of date on my machine. Fixed by running

```
pip install boto --upgrade
```

**Comment by tsileo** [comment]
Glad you resolve your issue. Don't hesitate to let me know if you have any feedback/suggestion or an other issue !
