### ISSUE TITLE
Cant install bakthat due to "Could not find a version that satisfies the requirement byteformat"

### ISSUE THREAD

**Issue by kimpellikaan** [tsileo/bakthat#48]
Hi there,

It seems bakthat is a great backup framework and would love to test it but getting it up and running is kind of a pain till now.

I ran `pip install -U bakthat`

```
Downloading/unpacking bakthat
  Downloading bakthat-0.6.0.tar.gz
  Running setup.py egg_info for package bakthat

    warning: no files found matching 'test'
Requirement already up-to-date: aaargh in /usr/local/lib/python2.7/dist-packages (from bakthat)
Requirement already up-to-date: boto in /usr/local/lib/python2.7/dist-packages (from bakthat)
Downloading/unpacking pycrypto (from bakthat)
  Downloading pycrypto-2.6.tar.gz (443kB): 443kB downloaded
  Running setup.py egg_info for package pycrypto

Downloading/unpacking beefish (from bakthat)
  Downloading beefish-0.1.1.tar.gz
  Running setup.py egg_info for package beefish

Downloading/unpacking grandfatherson (from bakthat)
  Downloading GrandFatherSon-1.2.tar.gz
  Running setup.py egg_info for package grandfatherson

Downloading/unpacking peewee (from bakthat)
  Downloading peewee-2.1.4.tar.gz (819kB): 819kB downloaded
  Running setup.py egg_info for package peewee

Downloading/unpacking byteformat (from bakthat)
  Could not find a version that satisfies the requirement byteformat (from bakthat) (from versions: 0.1a, 0.2a)
Cleaning up...
No distributions matching the version for byteformat (from bakthat)
Storing complete log in /root/.pip/pip.log
```

I followed https://github.com/tsileo/bakthat/issues/26 which got me further but now I am stuck here. 

Any idea's?

**Comment by darkfn** [comment]
I've solved this, in my case there was some troubles with compiling `pycrypto` module.  So I installed this module from aptitude:

```
aptitude install python-dev
aptitude install python-crypto
```

After that I tried to install bakthat using `pip` but there was same error with byteformat. 
Finally, I tried to install from sources:

```
pip uninstall bakthat
git clone https://github.com/tsileo/bakthat.git
cd bakthat
sudo python setup.py install
```

And it works for me!

```
$ bakthat -h
     usage: bakthat [-h]

   {delete_older_than,rotate_backups,backup,show,configure,configure_backups_rotation,restore,delete,periodic_backups,sync,reset_sync}
           ...
```

Hope, it would help you.

**Comment by kimpellikaan** [comment]
Thanks, it worked!

Only now I am facing new issues:

```
bakthat configure
```

```
Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.6.0', 'console_scripts', 'bakthat')()
  File "/usr/local/lib/python2.7/dist-packages/bakthat-0.6.0-py2.7.egg/bakthat/__init__.py", line 649, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/aaargh.py", line 157, in run
    return func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bakthat-0.6.0-py2.7.egg/bakthat/__init__.py", line 411, in configure
    new_conf = config.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

```

Any idea?

**Comment by kimpellikaan** [comment]
Acctualy it did not work at all. Anything I try gives back the above error. 

Are you sure its working for you?

Kim

**Comment by darkfn** [comment]
You should try

```
sudo bakthat configure
```

**Comment by kimpellikaan** [comment]
Hero!

I was executing the script as root so never though of it, nice!

**Comment by kimpellikaan** [comment]
The framework seems to work very well. 

Do you have an idea how long it takes for the files to show in the vault?

**Comment by ptone** [comment]
On a related note, in case others come here looking for info - the 1.4 release of pip won't install the pre-release of byteformat without the --pre flag on the pip command

**Comment by smola** [comment]
I'm hitting this bug too. Note that I got it installed by following @ptone's suggestion:

```
pip install --pre bakthat
```
