### ISSUE TITLE
Bakthat fails if compression is disabled and Directory is selected for backup.

### ISSUE THREAD

**Issue by hilt86** [tsileo/bakthat#55]
Bakthat fails if compression is disabled and Directory is selected for backup.

There is no version argument for Bakthat but from the /usr/local/bin/bakthat file it looks like I am running 0.6. Nevertheless here is the output 

$ bakthat backup vms/

Compression disabled
Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.6.0', 'console_scripts', 'bakthat')()
  File "/usr/local/lib/python2.7/dist-packages/bakthat/**init**.py", line 649, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/aaargh.py", line 157, in run
    return func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bakthat/**init**.py", line 301, in backup
    with open(outname) as outfile:

**Comment by amohrhard** [comment]
Experiencing the same here with 0.6.0.

**Comment by hilt86** [comment]
Any news on this @tsileo ?

**Comment by noisufnoc** [comment]
same problem.
