### ISSUE TITLE
Missing support for Tenant Name in Swift

### ISSUE THREAD

**Issue by CLloyd24** [tsileo/bakthat#66]
When attempting to use the Swift with Dreamobjects I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.6.0', 'console_scripts', 'bakthat')()
  File "/usr/local/lib/python2.7/dist-packages/bakthat/__init__.py", line 649, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/aaargh/app.py", line 176, in run
    return func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bakthat/__init__.py", line 245, in backup
    storage_backend, destination, conf = _get_store_backend(config, destination, profile)
  File "/usr/local/lib/python2.7/dist-packages/bakthat/__init__.py", line 57, in _get_store_backend
    return STORAGE_BACKEND[destination](conf, profile), destination, conf
  File "/usr/local/lib/python2.7/dist-packages/bakthat/backends.py", line 311, in __init__
    self.con.put_container(self.conf["s3_bucket"])
  File "/usr/lib/python2.7/dist-packages/swiftclient/client.py", line 1182, in put_container
    response_dict=response_dict)
  File "/usr/lib/python2.7/dist-packages/swiftclient/client.py", line 1103, in _retry
    self.url, self.token = self.get_auth()
  File "/usr/lib/python2.7/dist-packages/swiftclient/client.py", line 1079, in get_auth
    insecure=self.insecure)
  File "/usr/lib/python2.7/dist-packages/swiftclient/client.py", line 295, in get_auth
    raise ClientException('No tenant specified')
swiftclient.exceptions.ClientException: No tenant specified
```

This is also observed by another user here: http://thomassileo.com/blog/2013/04/24/bakthat-0-dot-5-0-released-with-openstack-swift-support-and-bakmanager-integration/

**Comment by CLloyd24** [comment]
Nevermind. It appears DreamObjects does not support Auth Version 2.

**Comment by elthariel** [comment]
Still a valid issue. Same problem here with cloudwatt

**Comment by quetzal** [comment]
Hello,

It's support tenant, but it's not well documented. In your configuration:
access_key: tenant_name:openstack_id

(if your tenant is 000000 and your id azerty, access_key: 000000:azerty).

**Comment by elthariel** [comment]
It should be in the documentation somewhere :-/

In the meantime I implemented swift into the ruby backup gem and used that

**Comment by quetzal** [comment]
Full swift support is not well documented. I've just setuped it for my backups and I can only find http://bakthat.readthedocs.io/en/latest/user_guide.html#openstack-swift-support (ACCOUNT:USER need to be explicited)
