### ISSUE TITLE
Restore dies with "Killed" and no other info

### ISSUE THREAD

**Issue by tk422** [tsileo/bakthat#9]
Hey there, 

The last python fixes worked fine, I am able to upload fine but when I go to restore a large file (16GB) I get the following:

root@dagobah:/home/ecarter# bakthat restore -f dantooine.253.tar.gz -d glacier
2013-02-13 11:06:11,890 INFO: Restoring dantooine.253.tar.gz20130212120602.tgz.enc
Password: 
2013-02-13 11:06:22,036 INFO: Downloading...
2013-02-13 11:06:22,132 INFO: Job ArchiveRetrieval: Succeeded (2013-02-12T20:47:54.042Z/2013-02-13T00:47:58.206Z)
2013-02-13 11:06:22,132 INFO: Downloading...
Killed

There is no other information, I have looked at the source code and didnt see anything that stuck out at me. Is the file being loaded into memory first (could it be running out of memory while downloading?)  I also didnt see any files in /tmp that appeared to be growing while running.

Let me know what I can do to debug. Thanks.

**Comment by tsileo** [comment]
Hi,

You're right, there was a bug when downloading the job output from Glacier, now the file is downloaded chunk by chunk, now at any moment the file is never fully loaded in memory,

So everything should be OK, I updated both github and pypi (released 0.3.6).

I hope the job is always available so you can test out quickly.

Thanks,
Le me know if you have any other issues/suggestions !

**Comment by tk422** [comment]
Hmmm just tried it and now get a nonetype error:

@dagobah:/home/ecar# bakthat restore -f dantooine.253.tar.gz -d glacier
2013-02-15 12:14:41,368 INFO: Restoring dantooine.253.tar.gz20130212120602.tgz.enc
Password: 
2013-02-15 12:14:42,866 INFO: Downloading...
Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.3.6', 'console_scripts', 'bakthat')()
  File "/usr/local/bin/bakthat.py", line 575, in main
    app.run()
  File "/usr/local/lib/python2.6/dist-packages/aaargh.py", line 157, in run
    return func(*_kwargs)
  File "/usr/local/bin/bakthat.py", line 483, in restore
    out = storage_backend.download(key_name, *_download_kwargs)
  File "/usr/local/bin/bakthat.py", line 262, in download
    del job[keyname]
TypeError: 'NoneType' object does not support item deletion

**Comment by tsileo** [comment]
You spot another bug, It failed to delete the job (after some times, the job disappear), it should be **jobs[keyname]**.

I updated the git repo, but not on pypi yet, install from git repository and now it should really be OK.

Please keep me updated,

Thanks !

**Comment by tk422** [comment]
Thanks. that seems to have fixed it.  Ill let you know if I still have problems with the large archive (waiting for it get retrieved so I can download it again).

**Comment by tk422** [comment]
Was able to start the retrieval again. Here is the new error:

013-02-16 11:44:31,468 INFO: Restoring dantooine.253.tar.gz20130212120602.tgz.enc
Password:
2013-02-16 11:45:37,016 INFO: Downloading...
2013-02-16 11:45:37,225 INFO: Job ArchiveRetrieval: Succeeded (2013-02-15T20:53:21.199Z/2013-02-16T00:53:23.679Z)
2013-02-16 11:45:37,225 INFO: Downloading...
Traceback (most recent call last):
  File "/usr/local/bin/bakthat", line 9, in <module>
    load_entry_point('bakthat==0.3.6', 'console_scripts', 'bakthat')()
  File "/usr/local/bin/bakthat.py", line 575, in main
    app.run()
  File "/usr/local/lib/python2.6/dist-packages/aaargh.py", line 157, in run
    return func(*_kwargs)
  File "/usr/local/bin/bakthat.py", line 483, in restore
    out = storage_backend.download(key_name, *_download_kwargs)
  File "/usr/local/bin/bakthat.py", line 283, in download
    True, (socket.error,))
  File "/usr/local/lib/python2.6/dist-packages/boto/glacier/job.py", line 127, in _download_to_fileob
    byte_range, retry_exceptions)
  File "/usr/local/lib/python2.6/dist-packages/boto/glacier/job.py", line 144, in _download_byte_range
    data = response.read()
  File "/usr/local/lib/python2.6/dist-packages/boto/glacier/response.py", line 48, in read
    return self.http_response.read(amt)
  File "/usr/local/lib/python2.6/dist-packages/boto/connection.py", line 409, in read
    self._cached_response = httplib.HTTPResponse.read(self)
  File "/usr/lib/python2.6/httplib.py", line 525, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.6/httplib.py", line 617, in _safe_read
    raise IncompleteRead(''.join(s), amt)
httplib.IncompleteRead: IncompleteRead(3145728 bytes read, 1048576 more expected)

**Comment by tsileo** [comment]
Hi,

This times, it seems to be a boto related issue, by default, they retry on a socket error but not on a IncompleteRead error,

Let me know if the fix works, I updated the repo,

Please keep me updated,

Thanks!

**Comment by tk422** [comment]
Looks like I tried again (before your fix and it worked so it doesnt occur
all the time). I will update now and see if its fixed after a couple of
tries.

**Comment by tsileo** [comment]
Glad to hear it worked, I think my last updated resolved your bug since it will retry to download only the last chunks.

Also, when seeing your backup's filename (dantooine.253.tar.gz20130212120602.tgz.enc), I realized that bakthat shouldn't compress an already compressed files.

So with the latest update, when you backup an already compressed files (.tgz./.tar.gz support only, and .tar.gz file will be renamed .tgz), compression is skipped, and when you restore it, the archive is automatically uncompressed, and it doesn't break encryption.

Let me know if you have any feedback,

Thanks !!

**Comment by tk422** [comment]
Did you update the pip version as well?

**Comment by tsileo** [comment]
I just pushed 0.3.7 on pypi just few minutes ago.
